name: "Mypy"
on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  run_mypy:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Narex dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
        
      - name: Run mypy
        run: mypy . --config-file pyproject.toml --verbose
